# Generated by Django 4.0.7 on 2022-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateField()),
                ('return_time', models.DateField()),
                ('station_id', models.IntegerField()),
                ('departure_station', models.CharField(max_length=120)),
                ('destination_id', models.IntegerField()),
                ('destination', models.CharField(max_length=120)),
                ('distance', models.FloatField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
